title:             BEEUC
email:             info@beeuc.com
description:       Development Blog
author:            beeuc
baseurl:           "/develop"
url:               "https://www.beeuc.com"

# Social Profiles
#twitter_username:  SBootstrap
github_username:   beeuc-corp
#facebook_username: StartBootstrap

# Build settings
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rough
    enable_coderay: true
    syntax_highlighter_opts: 
        wrap: div
        css: style


paginate: 5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
